### ISSUE TITLE
file already exists, symlink : when running tns livesync android --watch

### ISSUE THREAD

**Issue by robophil** [toddanglin/nativescript-dev-sass#15]
I keep getting the error when executing `tns run, livesync, build` etc. I end up deleting the `node_modules`, `hooks` and `platforms` to fix it and move on. Any solution to this permanently?
```bash
Executing before-prepare hook from /home/philip/NativeScriptProjects/BlueCollar/hooks/before-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook from /home/philip/NativeScriptProjects/BlueCollar/hooks/before-prepare/nativescript-dev-sass.js
Executing before-prepare hook from /home/philip/NativeScriptProjects/BlueCollar/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.0.10
shell.js: internal error
Error: EEXIST: file already exists, symlink '../node-sass/bin/node-sass' -> '/home/philip/NativeScriptProjects/BlueCollar/platforms/android/src/main/assets/app/tns_modules/nativescript-dev-sass/node_modules/.bin/node-sass'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:76:10)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at /usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:183:9
    at Array.forEach (native)
    at Object._cp (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:157:11)
    at Object.cp (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/common.js:186:23)
    at TnsModulesCopy.copyDependencyDir (/usr/local/lib/node_modules/nativescript/lib/tools/node-modules/node-modules-dest-copy.js:42:21)
    at _loop_1 (/usr/local/lib/node_modules/nativescript/lib/tools/node-modules/node-modules-dest-copy.js:17:20)
    at TnsModulesCopy.copyModules (/usr/local/lib/node_modules/nativescript/lib/tools/node-modules/node-modules-dest-copy.js:31:13)
    at /usr/local/lib/node_modules/nativescript/lib/tools/node-modules/node-modules-builder.js:129:32
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:267:117

```

**Comment by toddanglin** [comment]
I've not encountered this problem, so not quite sure how to debug.

Based on a quick Google search, it seems a number of other Node projects have encountered a similar error. I wonder if the problems are related? One [thread in the Ember project](https://github.com/ember-cli/ember-cli/issues/3413) suggests it's a bug in a lower level Node module. You might try some of the suggestions in those threads and see if solves your problem here.

In any event, if you can provide steps for reproducing the problem, I can try to make it happen locally.

**Comment by rsquared86** [comment]
i was getting a similar error and did tns platform remove ios then re-added it with tns platform add ios.

**Comment by toddanglin** [comment]
@rsquared86 Did that resolve the problem for you?

Still not sure what causes this issue to trigger. If you're able to provide steps to reproduce, happy to try to debug/look for a solution.

**Comment by rsquared86** [comment]
it did for a bit, but the issue resurfaced after a few builds. Not sure what the reproduction steps are yet, but if i narrow it down i'll post them.

**Comment by toddanglin** [comment]
Thanks @rsquared86. There is a big refactoring coming with 1.0.0 release, so that may further help eliminate this issue. Will close this for now, but if you run into the problem again with v1.0.0 or come-up with repro steps, we can re-open the issue.
